import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e7bcba',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'outline': '#ae8885',
        'outline-variant': '#5d3f3d',
        'surface-tint': '#ffb3af',
        'primary': '#ffb3af',
        'on-primary': '#68000e',
        'primary-container': '#d90429',
        'on-primary-container': '#ffeae8',
        'inverse-primary': '#bf0022',
        'secondary': '#ffb3b1',
        'on-secondary': '#680011',
        'secondary-container': '#d6022e',
        'on-secondary-container': '#ffe7e5',
        'tertiary': '#bbc7dd',
        'on-tertiary': '#253142',
        'tertiary-container': '#616d81',
        'on-tertiary-container': '#e8efff',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdad7',
        'primary-fixed-dim': '#ffb3af',
        'on-primary-fixed': '#410005',
        'on-primary-fixed-variant': '#930018',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#ffb3b1',
        'on-secondary-fixed': '#410007',
        'on-secondary-fixed-variant': '#92001c',
        'tertiary-fixed': '#d7e3fa',
        'tertiary-fixed-dim': '#bbc7dd',
        'on-tertiary-fixed': '#101c2c',
        'on-tertiary-fixed-variant': '#3c475a',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
      },
      fontFamily: {
        'display-xl': ['var(--font-anton)', 'Anton', 'sans-serif'],
        'display-xl-mobile': ['var(--font-anton)', 'Anton', 'sans-serif'],
        'headline-lg': ['var(--font-anton)', 'Anton', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-anton)', 'Anton', 'sans-serif'],
        'headline-md': ['var(--font-anton)', 'Anton', 'sans-serif'],
        'score-display': ['var(--font-anton)', 'Anton', 'sans-serif'],
        'headline-sm': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'body-lg': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'body-md': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'body-sm': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'label-lg': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'label-md': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'label-sm': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.1em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.08em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '26px', letterSpacing: '0.01em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '32px', letterSpacing: '0.04em', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '32px', letterSpacing: '0.03em', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '44px', letterSpacing: '0.03em', fontWeight: '400' }],
        'display-xl-mobile': ['44px', { lineHeight: '48px', letterSpacing: '0.02em', fontWeight: '400' }],
        'display-xl': ['72px', { lineHeight: '76px', letterSpacing: '0.02em', fontWeight: '400' }],
        'score-display': ['56px', { lineHeight: '56px', letterSpacing: '0.01em', fontWeight: '400' }],
      },
      spacing: {
        'gutter': '1.25rem',
        'gutter-desktop': '2rem',
        'margin': '1rem',
        'margin-desktop': '3rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'space-2xl': '4rem',
      },
      boxShadow: {
        'brutal': '4px 4px 0px 0px #d90429',
        'brutal-dark': '4px 4px 0px 0px #0e0e0e',
        'brutal-white': '4px 4px 0px 0px #ffffff',
        'glow-crimson': '0px 0px 24px -4px rgba(217, 4, 41, 0.45)',
      },
    },
  },
  plugins: [],
};

export default config;
